In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [3]:
df = pd.read_csv('bank_note_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [4]:
first_and_second_columns = ddf.iloc[:, :2]
first_and_second_columns

variance  skewness
0      3.62160   8.66610
1      4.54590   8.16740
2      3.86600  -2.63830
3      3.45660   9.52280
4      0.32924  -4.45520
...        ...       ...
1367   0.40614   1.34920
1368  -1.38870  -4.87730
1369  -3.75030 -13.45860
1370  -3.56370  -8.38270
1371  -2.54190  -0.65804

[1372 rows x 2 columns]

In [5]:
df.to_string() 

'      variance   skewness   curtosis   entropy  class\n0     3.621600   8.666100  -2.807300 -0.446990      0\n1     4.545900   8.167400  -2.458600 -1.462100      0\n2     3.866000  -2.638300   1.924200  0.106450      0\n3     3.456600   9.522800  -4.011200 -3.594400      0\n4     0.329240  -4.455200   4.571800 -0.988800      0\n5     4.368400   9.671800  -3.960600 -3.162500      0\n6     3.591200   3.012900   0.728880  0.564210      0\n7     2.092200  -6.810000   8.463600 -0.602160      0\n8     3.203200   5.758800  -0.753450 -0.612510      0\n9     1.535600   9.177200  -2.271800 -0.735350      0\n10    1.224700   8.777900  -2.213500 -0.806470      0\n11    3.989900  -2.706600   2.394600  0.862910      0\n12    1.899300   7.662500   0.153940 -3.110800      0\n13   -1.576800  10.843000   2.546200 -2.936200      0\n14    3.404000   8.726100  -2.991500 -0.572420      0\n15    4.676500  -3.389500   3.489600  1.477100      0\n16    2.671900   3.064600   0.371580  0.586190      0\n17    0.8

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr.ndim 

2

In [9]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [12]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4]) 

[1 2 3 4]


In [15]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Join the arrays along the existing axis
# result = np.concatenate((arr1, arr2)) #use concatenate or hstack
result = np.stack((arr1, arr2), axis=0) #use stack of vstack result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [19]:
arr = np.array([1,4,3,4,5,4,4])
 

In [20]:
np.where(arr == 4) 

(array([1, 3, 5, 6], dtype=int64),)

In [21]:
# Generate 1000 numbers with a normal distribution
# Mean = 50, Standard Deviation = 0.2
data = np.random.normal(loc=50, scale=0.2, size=1000)

print(data)

# Explanation:
# loc=50: The mean (center) of the distribution.
# scale=0.2: The standard deviation (spread or width) of the distribution.
# size=1000: The number of samples to generate.

[50.04733703 49.64140348 49.79284632 49.93113678 49.66444205 50.19906318
 49.99278455 50.08397225 49.53663653 50.16774387 49.93155136 49.83663751
 49.73393003 50.27093069 50.13588326 50.39511185 50.14499898 50.28437725
 50.07426605 50.10618293 49.91605728 50.24142295 50.19234924 50.19988822
 49.99538455 49.93965309 50.00627003 49.81741424 49.92749296 50.01003873
 50.09780575 49.87254585 50.19771668 49.80607542 50.2076791  49.80989447
 50.10850298 49.91487753 50.14148902 50.04457856 50.16386922 50.19076307
 50.17778802 50.05084794 49.85942418 50.01726943 49.90871246 50.05730674
 49.74056935 49.77840933 50.27724051 50.12280354 50.02380802 50.39458465
 50.12692763 49.88947864 49.78538871 50.06584172 49.74408304 50.37821692
 50.22929956 49.45799696 50.33645894 49.88843413 50.17071664 50.11943834
 49.77712896 49.80311827 50.06039783 49.95146496 50.239463   49.6973617
 49.81020713 49.96772617 50.11853123 50.169391   49.65827778 49.91341248
 50.20937002 49.93735308 50.02535096 50.12173605 49.

In [22]:
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]


In [26]:
tempdict ={'col1':[1,2,3], 'col2':[4,5,6], 'col3':[7,8,9]}

In [28]:
dictdf = pd.DataFrame.from_dict(tempdict)
dictdf

col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [49]:
df = pd.read_csv('telco_churn.csv')
df.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1            110.0   
1                     26              161.6            123.0   
2                      0              243.4            114.0   
3                      0              299.4             71.0   
4                      0              166.7            113.0   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4             99.0             16.78   
1             27.47              195.5            103.0             16.62   
2             41.38              121.2            110.0             10.30   
3             50.90               61.9             88.0              5.26   
4             28.34              148.3            122.0             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7               91.0               11.01   
1                254.4              103.0               11.45   
2                162.6              104.0                7.32   
3                196.9               89.0                8.86   
4                186.9              121.0                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                     1.0  False  
1                     1.0  False  
2                     0.0  False  
3                     2.0  False  
4                     3.0  False

In [31]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [32]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [34]:
df.describe()

Account length    Area code  Number vmail messages  Total day minutes  \
count     3333.000000  3333.000000            3333.000000        3323.000000   
mean       101.064806   437.182418               8.099010         179.787150   
std         39.822106    42.371290              13.688365          54.419625   
min          1.000000   408.000000               0.000000           0.000000   
25%         74.000000   408.000000               0.000000         143.700000   
50%        101.000000   415.000000               0.000000         179.400000   
75%        127.000000   510.000000              20.000000         216.500000   
max        243.000000   510.000000              51.000000         350.800000   

       Total day calls  Total day charge  Total eve minutes  Total eve calls  \
count      3323.000000       3315.000000        3324.000000      3325.000000   
mean        100.456214         30.557831         201.033935       100.110677   
std          20.057356          9.255987          50.676652        19.932115   
min           0.000000          0.000000           0.000000         0.000000   
25%          87.000000         24.420000         166.600000        87.000000   
50%         101.000000         30.500000         201.400000       100.000000   
75%         114.000000         36.780000         235.325000       114.000000   
max         165.000000         59.640000         363.700000       170.000000   

       Total eve charge  Total night minutes  Total night calls  \
count       3333.000000          3333.000000        3332.000000   
mean          17.083540           200.872037         100.115246   
std            4.310668            50.573847          19.566710   
min            0.000000            23.200000          33.000000   
25%           14.160000           167.000000          87.000000   
50%           17.120000           201.200000         100.000000   
75%           20.000000           235.300000         113.000000   
max           30.910000           395.000000         175.000000   

       Total night charge  Total intl minutes  Total intl calls  \
count         3333.000000         3333.000000       3333.000000   
mean             9.039325           10.237294          4.479448   
std              2.275873            2.791840          2.461214   
min              1.040000            0.000000          0.000000   
25%              7.520000            8.500000          3.000000   
50%              9.050000           10.300000          4.000000   
75%             10.590000           12.100000          6.000000   
max             17.770000           20.000000         20.000000   

       Total intl charge  Customer service calls  
count        3328.000000             3328.000000  
mean            2.764588                1.563101  
std             0.754086                1.315870  
min             0.000000                0.000000  
25%             2.300000                1.000000  
50%             2.780000                1.000000  
75%             3.270000                2.000000  
max             5.400000                9.000000

In [35]:
df.describe(include='object')

State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

In [36]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [37]:
value_counts = df['State'].value_counts()
value_counts

State
WV    106
MN     84
NY     83
AL     80
WI     78
OH     78
OR     78
WY     77
VA     77
CT     74
MI     73
ID     73
VT     73
TX     72
UT     72
IN     71
MD     70
KS     70
NC     68
NJ     68
MT     68
CO     66
NV     66
WA     66
RI     65
MA     65
MS     65
AZ     64
FL     63
MO     63
NM     62
ME     62
ND     62
NE     61
OK     61
DE     61
SC     60
SD     60
KY     59
IL     58
NH     56
AR     55
GA     54
DC     54
HI     53
TN     53
AK     52
LA     51
PA     45
IA     44
CA     34
Name: count, dtype: int64

In [38]:
df['International plan']

0        No
1        No
2        No
3       Yes
4       Yes
       ... 
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [42]:
df[['State','International plan']]

State International plan
0       KS                 No
1       OH                 No
2       NJ                 No
3       OH                Yes
4       OK                Yes
...    ...                ...
3328    AZ                 No
3329    WV                 No
3330    RI                 No
3331    CT                Yes
3332    TN                 No

[3333 rows x 2 columns]

In [41]:
df.State.unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

In [44]:
df.Churn.unique()

array([False, nan, True], dtype=object)

In [45]:
df[df['International plan']== 'No']

State  Account length  Area code International plan Voice mail plan  \
0       KS             128        415                 No             Yes   
1       OH             107        415                 No             Yes   
2       NJ             137        415                 No              No   
6       MA             121        510                 No             Yes   
8       LA             117        408                 No              No   
...    ...             ...        ...                ...             ...   
3327    SC              79        415                 No              No   
3328    AZ             192        415                 No             Yes   
3329    WV              68        415                 No              No   
3330    RI              28        510                 No              No   
3332    TN              74        415                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1            110.0   
1                        26              161.6            123.0   
2                         0              243.4            114.0   
6                        24              218.2             88.0   
8                         0              184.5             97.0   
...                     ...                ...              ...   
3327                      0              134.7             98.0   
3328                     36              156.2             77.0   
3329                      0              231.1             57.0   
3330                      0              180.8            109.0   
3332                     25              234.4            113.0   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                45.07              197.4             99.0             16.78   
1                27.47              195.5            103.0             16.62   
2                41.38              121.2            110.0             10.30   
6                37.09              348.5            108.0             29.62   
8                31.37              351.6             80.0             29.89   
...                ...                ...              ...               ...   
3327             22.90              189.7             68.0             16.12   
3328             26.55              215.5            126.0             18.32   
3329             39.29              153.4             55.0             13.04   
3330             30.74              288.8             58.0             24.55   
3332             39.85              265.9             82.0             22.60   

      Total night minutes  Total night calls  Total night charge  \
0                   244.7               91.0               11.01   
1                   254.4              103.0               11.45   
2                   162.6              104.0                7.32   
6                   212.6              118.0                9.57   
8                   215.8               90.0                9.71   
...                   ...                ...                 ...   
3327                221.4              128.0                9.96   
3328                279.1               83.0               12.56   
3329                191.3              123.0                8.61   
3330                191.9               91.0                8.64   
3332                241.4               77.0               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
6                    7.5                 7               2.03   
8                    8.7                 4               2.35   
...                  ...               ...                ...   
3327                11.8                 5            

In [46]:
df[(df['International plan']== 'No')  & (df['Churn']==False)] 

State  Account length  Area code International plan Voice mail plan  \
0       KS             128        415                 No             Yes   
1       OH             107        415                 No             Yes   
2       NJ             137        415                 No              No   
8       LA             117        408                 No              No   
11      RI              74        415                 No              No   
...    ...             ...        ...                ...             ...   
3327    SC              79        415                 No              No   
3328    AZ             192        415                 No             Yes   
3329    WV              68        415                 No              No   
3330    RI              28        510                 No              No   
3332    TN              74        415                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1            110.0   
1                        26              161.6            123.0   
2                         0              243.4            114.0   
8                         0              184.5             97.0   
11                        0              187.7            127.0   
...                     ...                ...              ...   
3327                      0              134.7             98.0   
3328                     36              156.2             77.0   
3329                      0              231.1             57.0   
3330                      0              180.8            109.0   
3332                     25              234.4            113.0   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                45.07              197.4             99.0             16.78   
1                27.47              195.5            103.0             16.62   
2                41.38              121.2            110.0             10.30   
8                31.37              351.6             80.0             29.89   
11               31.91              163.4            148.0             13.89   
...                ...                ...              ...               ...   
3327             22.90              189.7             68.0             16.12   
3328             26.55              215.5            126.0             18.32   
3329             39.29              153.4             55.0             13.04   
3330             30.74              288.8             58.0             24.55   
3332             39.85              265.9             82.0             22.60   

      Total night minutes  Total night calls  Total night charge  \
0                   244.7               91.0               11.01   
1                   254.4              103.0               11.45   
2                   162.6              104.0                7.32   
8                   215.8               90.0                9.71   
11                  196.0               94.0                8.82   
...                   ...                ...                 ...   
3327                221.4              128.0                9.96   
3328                279.1               83.0               12.56   
3329                191.3              123.0                8.61   
3330                191.9               91.0                8.64   
3332                241.4               77.0               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
8                    8.7                 4               2.35   
11                   9.1                 5               2.46   
...                  ...               ...                ...   
3327                11.8                 5            

In [47]:
count = df[(df['International plan'] == 'No') & (df['Churn'] == False)].shape[0]
print(count)

2656


In [48]:
df.iloc[4] # sampel data at row number 5

State                        OK
Account length               75
Area code                   415
International plan          Yes
Voice mail plan              No
Number vmail messages         0
Total day minutes         166.7
Total day calls           113.0
Total day charge          28.34
Total eve minutes         148.3
Total eve calls           122.0
Total eve charge          12.61
Total night minutes       186.9
Total night calls         121.0
Total night charge         8.41
Total intl minutes         10.1
Total intl calls              3
Total intl charge          2.73
Customer service calls      3.0
Churn                     False
Name: 4, dtype: object

In [51]:
df.iloc[4,-1] #4 is row number, -1 is column number

False

In [54]:
df.iloc[1:4] #prints row number 1 until 3

State  Account length  Area code International plan Voice mail plan  \
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
1                     26              161.6            123.0   
2                      0              243.4            114.0   
3                      0              299.4             71.0   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
1             27.47              195.5            103.0             16.62   
2             41.38              121.2            110.0             10.30   
3             50.90               61.9             88.0              5.26   

   Total night minutes  Total night calls  Total night charge  \
1                254.4              103.0               11.45   
2                162.6              104.0                7.32   
3                196.9               89.0                8.86   

   Total intl minutes  Total intl calls  Total intl charge  \
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   

   Customer service calls  Churn  
1                     1.0  False  
2                     0.0  False  
3                     2.0  False

In [55]:
state = df.copy()
state.set_index('State', inplace=True)

In [56]:
state.head()

Account length  Area code International plan Voice mail plan  \
State                                                                 
KS                128        415                 No             Yes   
OH                107        415                 No             Yes   
NJ                137        415                 No              No   
OH                 84        408                Yes              No   
OK                 75        415                Yes              No   

       Number vmail messages  Total day minutes  Total day calls  \
State                                                              
KS                        25              265.1            110.0   
OH                        26              161.6            123.0   
NJ                         0              243.4            114.0   
OH                         0              299.4             71.0   
OK                         0              166.7            113.0   

       Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
State                                                                           
KS                45.07              197.4             99.0             16.78   
OH                27.47              195.5            103.0             16.62   
NJ                41.38              121.2            110.0             10.30   
OH                50.90               61.9             88.0              5.26   
OK                28.34              148.3            122.0             12.61   

       Total night minutes  Total night calls  Total night charge  \
State                                                               
KS                   244.7               91.0               11.01   
OH                   254.4              103.0               11.45   
NJ                   162.6              104.0                7.32   
OH                   196.9               89.0                8.86   
OK                   186.9              121.0                8.41   

       Total intl minutes  Total intl calls  Total intl charge  \
State                                                            
KS                   10.0                 3               2.70   
OH                   13.7                 3               3.70   
NJ                   12.2                 5               3.29   
OH                    6.6                 7               1.78   
OK                   10.1                 3               2.73   

       Customer service calls  Churn  
State                                 
KS                        1.0  False  
OH                        1.0  False  
NJ                        0.0  False  
OH                        2.0  False  
OK                        3.0  False

In [57]:
state.loc['OH']

Account length  Area code International plan Voice mail plan  \
State                                                                 
OH                107        415                 No             Yes   
OH                 84        408                Yes              No   
OH                 65        408                 No              No   
OH                 83        415                 No              No   
OH                 63        415                Yes             Yes   
...               ...        ...                ...             ...   
OH                160        415                 No              No   
OH                 88        408                 No              No   
OH                106        415                 No             Yes   
OH                 78        408                 No              No   
OH                 96        415                 No              No   

       Number vmail messages  Total day minutes  Total day calls  \
State                                                              
OH                        26              161.6            123.0   
OH                         0              299.4             71.0   
OH                         0              187.9            116.0   
OH                         0              337.4            120.0   
OH                        36              199.0            110.0   
...                      ...                ...              ...   
OH                         0              206.3             66.0   
OH                         0              274.6            105.0   
OH                        30              220.1            105.0   
OH                         0              193.4             99.0   
OH                         0              106.6            128.0   

       Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
State                                                                           
OH                27.47              195.5            103.0             16.62   
OH                50.90               61.9             88.0              5.26   
OH                31.94              157.6            117.0             13.40   
OH                57.36              227.4            116.0             19.33   
OH                33.83              291.3            111.0             24.76   
...                 ...                ...              ...               ...   
OH                35.07              241.1            109.0             20.49   
OH                46.68              161.1            121.0             13.69   
OH                37.42              222.2            109.0             18.89   
OH                32.88              116.9             88.0              9.94   
OH                18.12              284.8             87.0             24.21   

       Total night minutes  Total night calls  Total night charge  \
State                                                               
OH                   254.4              103.0               11.45   
OH                   196.9               89.0                8.86   
OH                   227.3               86.0               10.23   
OH                   153.9              114.0                6.93   
OH                   197.6               92.0                8.89   
...                    ...                ...                 ...   
OH                   227.8              102.0               10.25   
OH                   194.4              123.0                8.75   
OH                   158.4               96.0                7.13   
OH                   243.3              109.0               10.95   
OH                   178.9               92.0                8.05   

       Total intl minutes  Total intl calls  Total intl charge  \
State                                                            
OH                   13.7                 3               3.70   
OH                    6.6                 7     

In [58]:
df.isnull().sum() # few columns have missing values. need to drop them

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [61]:
df.dropna(inplace=True)

In [62]:
df.isnull().sum()  # no more missing values after they are dropped

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [64]:
df.drop('Area code', axis=1) # dropping columns - axis 1 is because dropping columns (0 indicates column)

State  Account length International plan Voice mail plan  \
0       KS             128                 No             Yes   
1       OH             107                 No             Yes   
2       NJ             137                 No              No   
3       OH              84                Yes              No   
4       OK              75                Yes              No   
...    ...             ...                ...             ...   
3328    AZ             192                 No             Yes   
3329    WV              68                 No              No   
3330    RI              28                 No              No   
3331    CT             184                Yes              No   
3332    TN              74                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1            110.0   
1                        26              161.6            123.0   
2                         0              243.4            114.0   
3                         0              299.4             71.0   
4                         0              166.7            113.0   
...                     ...                ...              ...   
3328                     36              156.2             77.0   
3329                      0              231.1             57.0   
3330                      0              180.8            109.0   
3331                      0              213.8            105.0   
3332                     25              234.4            113.0   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                45.07              197.4             99.0             16.78   
1                27.47              195.5            103.0             16.62   
2                41.38              121.2            110.0             10.30   
3                50.90               61.9             88.0              5.26   
4                28.34              148.3            122.0             12.61   
...                ...                ...              ...               ...   
3328             26.55              215.5            126.0             18.32   
3329             39.29              153.4             55.0             13.04   
3330             30.74              288.8             58.0             24.55   
3331             36.35              159.6             84.0             13.57   
3332             39.85              265.9             82.0             22.60   

      Total night minutes  Total night calls  Total night charge  \
0                   244.7               91.0               11.01   
1                   254.4              103.0               11.45   
2                   162.6              104.0                7.32   
3                   196.9               89.0                8.86   
4                   186.9              121.0                8.41   
...                   ...                ...                 ...   
3328                279.1               83.0               12.56   
3329                191.3              123.0                8.61   
3330                191.9               91.0                8.64   
3331                139.2              137.0                6.26   
3332                241.4               77.0               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
3                    6.6                 7               1.78   
4                   10.1                 3               2.73   
...                  ...               ...                ...   
3328                 9.9                 6               2.67   
3329                 9.6                 4               2.59   
3330                14.1                 6              

In [71]:
df['New Column'] = df['Total night minutes'] + df['Total intl minutes'] # creating a new calculated column

In [72]:
df['New Column'] = 100 # updating the entire new column to 100

In [73]:
df.head() # new column was added

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1            110.0   
1                     26              161.6            123.0   
2                      0              243.4            114.0   
3                      0              299.4             71.0   
4                      0              166.7            113.0   

   Total day charge  Total eve minutes  ...  Total eve charge  \
0             45.07              197.4  ...             16.78   
1             27.47              195.5  ...             16.62   
2             41.38              121.2  ...             10.30   
3             50.90               61.9  ...              5.26   
4             28.34              148.3  ...             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7               91.0               11.01   
1                254.4              103.0               11.45   
2                162.6              104.0                7.32   
3                196.9               89.0                8.86   
4                186.9              121.0                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn New Column  
0                     1.0  False        100  
1                     1.0  False        100  
2                     0.0  False        100  
3                     2.0  False        100  
4                     3.0  False        100  

[5 rows x 21 columns]

In [74]:
df.iloc[0,-1]=10 # updating a single value

In [75]:
df.head(3)

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1            110.0   
1                     26              161.6            123.0   
2                      0              243.4            114.0   

   Total day charge  Total eve minutes  ...  Total eve charge  \
0             45.07              197.4  ...             16.78   
1             27.47              195.5  ...             16.62   
2             41.38              121.2  ...             10.30   

   Total night minutes  Total night calls  Total night charge  \
0                244.7               91.0               11.01   
1                254.4              103.0               11.45   
2                162.6              104.0                7.32   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   

   Customer service calls  Churn New Column  
0                     1.0  False         10  
1                     1.0  False        100  
2                     0.0  False        100  

[3 rows x 21 columns]

In [77]:
df['Churn Binary'] = df['Churn'].apply(lambda x: 1 if x==True else 0) # create a new column churn binary. put a condition using apply lambda method

In [78]:
df[df['Churn']==True].head()

State  Account length  Area code International plan Voice mail plan  \
10    IN              65        415                 No              No   
41    MD             135        408                Yes             Yes   
48    ID             119        415                 No              No   
54    WY              87        415                 No              No   
57    CO             121        408                 No             Yes   

    Number vmail messages  Total day minutes  Total day calls  \
10                      0              129.1            137.0   
41                     41              173.1             85.0   
48                      0              159.1            114.0   
54                      0              151.0             83.0   
57                     30              198.4            129.0   

    Total day charge  Total eve minutes  ...  Total night minutes  \
10             21.95              228.5  ...                208.8   
41             29.43              203.9  ...                122.2   
48             27.05              231.3  ...                143.2   
54             25.67              219.7  ...                203.9   
57             33.73               75.3  ...                181.2   

    Total night calls  Total night charge  Total intl minutes  \
10              111.0                9.40                12.7   
41               78.0                5.50                14.6   
48               91.0                6.44                 8.8   
54              127.0                9.18                 9.7   
57               77.0                8.15                 5.8   

    Total intl calls  Total intl charge  Customer service calls  Churn  \
10                 6               3.43                     4.0   True   
41                15               3.94                     0.0   True   
48                 3               2.38                     5.0   True   
54                 3               2.62                     5.0   True   
57                 3               1.57                     3.0   True   

    New Column Churn Binary  
10         100            1  
41         100            1  
48         100            1  
54         100            1  
57         100            1  

[5 rows x 22 columns]

In [ ]:
# df.to_csv('outputshshs') # output to csv

In [79]:
# df.to_json() # output to json

In [80]:
# df.to_html() # output to html

In [ ]:
# del df # delte dataframe